# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from diarizen.proto import ux_speaker_diarization_pb2 as diarizen_dot_proto_dot_ux__speaker__diarization__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in diarizen/proto/ux_speaker_diarization_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UxSpeakerDiarizationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Detect = channel.unary_unary(
                '/ux_sd.UxSpeakerDiarization/Detect',
                request_serializer=diarizen_dot_proto_dot_ux__speaker__diarization__pb2.DetectRequest.SerializeToString,
                response_deserializer=diarizen_dot_proto_dot_ux__speaker__diarization__pb2.DetectResponse.FromString,
                _registered_method=True)
        self.DetectWav = channel.unary_unary(
                '/ux_sd.UxSpeakerDiarization/DetectWav',
                request_serializer=diarizen_dot_proto_dot_ux__speaker__diarization__pb2.DetectWavRequest.SerializeToString,
                response_deserializer=diarizen_dot_proto_dot_ux__speaker__diarization__pb2.DetectResponse.FromString,
                _registered_method=True)


class UxSpeakerDiarizationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Detect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetectWav(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UxSpeakerDiarizationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Detect': grpc.unary_unary_rpc_method_handler(
                    servicer.Detect,
                    request_deserializer=diarizen_dot_proto_dot_ux__speaker__diarization__pb2.DetectRequest.FromString,
                    response_serializer=diarizen_dot_proto_dot_ux__speaker__diarization__pb2.DetectResponse.SerializeToString,
            ),
            'DetectWav': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectWav,
                    request_deserializer=diarizen_dot_proto_dot_ux__speaker__diarization__pb2.DetectWavRequest.FromString,
                    response_serializer=diarizen_dot_proto_dot_ux__speaker__diarization__pb2.DetectResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ux_sd.UxSpeakerDiarization', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ux_sd.UxSpeakerDiarization', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UxSpeakerDiarization(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Detect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ux_sd.UxSpeakerDiarization/Detect',
            diarizen_dot_proto_dot_ux__speaker__diarization__pb2.DetectRequest.SerializeToString,
            diarizen_dot_proto_dot_ux__speaker__diarization__pb2.DetectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DetectWav(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ux_sd.UxSpeakerDiarization/DetectWav',
            diarizen_dot_proto_dot_ux__speaker__diarization__pb2.DetectWavRequest.SerializeToString,
            diarizen_dot_proto_dot_ux__speaker__diarization__pb2.DetectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
