# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: diarizen/proto/ux_speaker_diarization.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'diarizen/proto/ux_speaker_diarization.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+diarizen/proto/ux_speaker_diarization.proto\x12\x05ux_sd\x1a\x1egoogle/protobuf/duration.proto\"\x8b\x01\n\x06\x43onfig\x12-\n\x08\x65ncoding\x18\x01 \x01(\x0e\x32\x1b.ux_sd.Config.AudioEncoding\x12\x19\n\x11sample_rate_hertz\x18\x02 \x01(\r\"7\n\rAudioEncoding\x12\x18\n\x14\x45NCODING_UNSPECIFIED\x10\x00\x12\x0c\n\x08LINEAR16\x10\x01\"?\n\x10\x44\x65tectWavRequest\x12\x1d\n\x06\x63onfig\x18\x01 \x01(\x0b\x32\r.ux_sd.Config\x12\x0c\n\x04path\x18\x02 \x01(\t\"=\n\rDetectRequest\x12\x1d\n\x06\x63onfig\x18\x01 \x01(\x0b\x32\r.ux_sd.Config\x12\r\n\x05\x61udio\x18\x02 \x01(\x0c\"9\n\x0e\x44\x65tectResponse\x12\'\n\x07results\x18\x01 \x03(\x0b\x32\x16.ux_sd.DetectionResult\"~\n\x0f\x44\x65tectionResult\x12-\n\nstart_time\x18\x01 \x01(\x0b\x32\x19.google.protobuf.Duration\x12+\n\x08\x65nd_time\x18\x02 \x01(\x0b\x32\x19.google.protobuf.Duration\x12\x0f\n\x07speaker\x18\x03 \x01(\r2\x8e\x01\n\x14UxSpeakerDiarization\x12\x37\n\x06\x44\x65tect\x12\x14.ux_sd.DetectRequest\x1a\x15.ux_sd.DetectResponse\"\x00\x12=\n\tDetectWav\x12\x17.ux_sd.DetectWavRequest\x1a\x15.ux_sd.DetectResponse\"\x00\x42)\n\tcom.ux.sdB\tUxSdProtoP\x01Z\x0fulang.com/sd;sdb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'diarizen.proto.ux_speaker_diarization_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\tcom.ux.sdB\tUxSdProtoP\001Z\017ulang.com/sd;sd'
  _globals['_CONFIG']._serialized_start=87
  _globals['_CONFIG']._serialized_end=226
  _globals['_CONFIG_AUDIOENCODING']._serialized_start=171
  _globals['_CONFIG_AUDIOENCODING']._serialized_end=226
  _globals['_DETECTWAVREQUEST']._serialized_start=228
  _globals['_DETECTWAVREQUEST']._serialized_end=291
  _globals['_DETECTREQUEST']._serialized_start=293
  _globals['_DETECTREQUEST']._serialized_end=354
  _globals['_DETECTRESPONSE']._serialized_start=356
  _globals['_DETECTRESPONSE']._serialized_end=413
  _globals['_DETECTIONRESULT']._serialized_start=415
  _globals['_DETECTIONRESULT']._serialized_end=541
  _globals['_UXSPEAKERDIARIZATION']._serialized_start=544
  _globals['_UXSPEAKERDIARIZATION']._serialized_end=686
# @@protoc_insertion_point(module_scope)
