"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import abc
import collections.abc
import diarizen.proto.ux_speaker_diarization_pb2
import grpc
import grpc.aio
import typing

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

class UxSpeakerDiarizationStub:
    def __init__(self, channel: typing.Union[grpc.Channel, grpc.aio.Channel]) -> None: ...
    Detect: grpc.UnaryUnaryMultiCallable[
        diarizen.proto.ux_speaker_diarization_pb2.DetectRequest,
        diarizen.proto.ux_speaker_diarization_pb2.DetectResponse,
    ]

    DetectWav: grpc.UnaryUnaryMultiCallable[
        diarizen.proto.ux_speaker_diarization_pb2.DetectWavRequest,
        diarizen.proto.ux_speaker_diarization_pb2.DetectResponse,
    ]

class UxSpeakerDiarizationAsyncStub:
    Detect: grpc.aio.UnaryUnaryMultiCallable[
        diarizen.proto.ux_speaker_diarization_pb2.DetectRequest,
        diarizen.proto.ux_speaker_diarization_pb2.DetectResponse,
    ]

    DetectWav: grpc.aio.UnaryUnaryMultiCallable[
        diarizen.proto.ux_speaker_diarization_pb2.DetectWavRequest,
        diarizen.proto.ux_speaker_diarization_pb2.DetectResponse,
    ]

class UxSpeakerDiarizationServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def Detect(
        self,
        request: diarizen.proto.ux_speaker_diarization_pb2.DetectRequest,
        context: _ServicerContext,
    ) -> typing.Union[diarizen.proto.ux_speaker_diarization_pb2.DetectResponse, collections.abc.Awaitable[diarizen.proto.ux_speaker_diarization_pb2.DetectResponse]]: ...

    @abc.abstractmethod
    def DetectWav(
        self,
        request: diarizen.proto.ux_speaker_diarization_pb2.DetectWavRequest,
        context: _ServicerContext,
    ) -> typing.Union[diarizen.proto.ux_speaker_diarization_pb2.DetectResponse, collections.abc.Awaitable[diarizen.proto.ux_speaker_diarization_pb2.DetectResponse]]: ...

def add_UxSpeakerDiarizationServicer_to_server(servicer: UxSpeakerDiarizationServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
