"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.duration_pb2
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Config(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _AudioEncoding:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _AudioEncodingEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Config._AudioEncoding.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        ENCODING_UNSPECIFIED: Config._AudioEncoding.ValueType  # 0
        """Not specified."""
        LINEAR16: Config._AudioEncoding.ValueType  # 1
        """16位有符号pcm (little-endian)"""

    class AudioEncoding(_AudioEncoding, metaclass=_AudioEncodingEnumTypeWrapper): ...
    ENCODING_UNSPECIFIED: Config.AudioEncoding.ValueType  # 0
    """Not specified."""
    LINEAR16: Config.AudioEncoding.ValueType  # 1
    """16位有符号pcm (little-endian)"""

    ENCODING_FIELD_NUMBER: builtins.int
    SAMPLE_RATE_HERTZ_FIELD_NUMBER: builtins.int
    encoding: global___Config.AudioEncoding.ValueType
    """音频编码"""
    sample_rate_hertz: builtins.int
    """采样率"""
    def __init__(
        self,
        *,
        encoding: global___Config.AudioEncoding.ValueType = ...,
        sample_rate_hertz: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["encoding", b"encoding", "sample_rate_hertz", b"sample_rate_hertz"]) -> None: ...

global___Config = Config

@typing.final
class DetectWavRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONFIG_FIELD_NUMBER: builtins.int
    PATH_FIELD_NUMBER: builtins.int
    path: builtins.str
    @property
    def config(self) -> global___Config: ...
    def __init__(
        self,
        *,
        config: global___Config | None = ...,
        path: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["config", b"config"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["config", b"config", "path", b"path"]) -> None: ...

global___DetectWavRequest = DetectWavRequest

@typing.final
class DetectRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONFIG_FIELD_NUMBER: builtins.int
    AUDIO_FIELD_NUMBER: builtins.int
    audio: builtins.bytes
    @property
    def config(self) -> global___Config: ...
    def __init__(
        self,
        *,
        config: global___Config | None = ...,
        audio: builtins.bytes = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["config", b"config"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["audio", b"audio", "config", b"config"]) -> None: ...

global___DetectRequest = DetectRequest

@typing.final
class DetectResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESULTS_FIELD_NUMBER: builtins.int
    @property
    def results(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___DetectionResult]: ...
    def __init__(
        self,
        *,
        results: collections.abc.Iterable[global___DetectionResult] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["results", b"results"]) -> None: ...

global___DetectResponse = DetectResponse

@typing.final
class DetectionResult(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    START_TIME_FIELD_NUMBER: builtins.int
    END_TIME_FIELD_NUMBER: builtins.int
    SPEAKER_FIELD_NUMBER: builtins.int
    speaker: builtins.int
    @property
    def start_time(self) -> google.protobuf.duration_pb2.Duration: ...
    @property
    def end_time(self) -> google.protobuf.duration_pb2.Duration: ...
    def __init__(
        self,
        *,
        start_time: google.protobuf.duration_pb2.Duration | None = ...,
        end_time: google.protobuf.duration_pb2.Duration | None = ...,
        speaker: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["end_time", b"end_time", "start_time", b"start_time"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["end_time", b"end_time", "speaker", b"speaker", "start_time", b"start_time"]) -> None: ...

global___DetectionResult = DetectionResult
